name: Deploy na Branch Main

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: curl --request POST '${{ secrets.RENDER_DEPLOY_HOOK }}'
